In [1]:
import torch

x=torch.arange(4.0)

In [2]:
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)#定义x用于保存梯度

tensor([0., 1., 2., 3.], requires_grad=True)

In [4]:
x.grad

In [5]:
print(x.grad)#说明现在还没有梯度

None


In [6]:
y=2*torch.dot(x,x)

In [7]:
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
t.backward()

NameError: name 't' is not defined

In [ ]:
y.backward()#反向传播，将计算的梯度存储到x中

In [ ]:
x.grad

In [9]:
x.grad == 4*x

False

In [10]:
x.grad.zero_()# 在默认情况下，PyTorch会累积梯度，需要清除之前的值

AttributeError: 'NoneType' object has no attribute 'zero_'

In [11]:
y=x.sum()#一个新的函数y=x1+x2+....

In [12]:
y.backward()

In [13]:
x.grad()

TypeError: 'Tensor' object is not callable

In [14]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [15]:
x.grad

tensor([1., 1., 1., 1.])

In [16]:
y.backward()#在进行一次，发现累积

In [17]:
x.grad

tensor([2., 2., 2., 2.])

In [18]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [19]:
y=x*x#对应元素相乘，变为y=[x1^2...]

In [20]:
y.sum().backward()#对z=x1^2+...进行反向传播，得到[2x1,2x2...]

In [21]:
x.grad

tensor([0., 2., 4., 6.])

In [22]:
x.grad==2*x

tensor([True, True, True, True])

In [23]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [24]:
y=x*x

In [25]:
u=y.detach()#该变量与y具有相同的值， 但丢弃计算图中如何计算y的任何信息。 换句话说，梯度不会向后流经u到x，而是把u当作常数

In [26]:
z=u*x

In [27]:
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [ ]:
x

In [28]:
x.grad

tensor([0., 0., 0., 0.])

In [29]:
z.sum().backward()

In [30]:
x.grad

tensor([0., 1., 4., 9.])

In [31]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [32]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [33]:
a.grad == d / a

tensor(True)

In [34]:
a = torch.randn(size=(), requires_grad=True)

In [35]:
a = torch.randn()

TypeError: randn() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [36]:
#2.5.6

In [37]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [38]:
y=x*x

In [39]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [40]:
y.sum().backward()

In [41]:
x.grad

tensor([0., 2., 4., 6.])

In [42]:
z = y.sum()

In [43]:
z.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [44]:
y=x**3

In [45]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [46]:
y=torch.dot(x,x)

In [47]:
y.backward()

In [48]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [49]:
x.grad.zero_()
y=torch.dot(x,x)
y.backward(retain_graph=True)#默认不允许连续backward,除非在第一次backward时y.backward(retain_graph=True),后续backward会累积
x.grad

tensor([0., 2., 4., 6.])

In [50]:
y.backward(retain_graph=True)

In [51]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [52]:
y.backward()
x.grad

tensor([ 0.,  6., 12., 18.])

In [53]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [59]:
def f(a):
    b=a*a
    return b
a1=torch.arange(3.0)
a1.requires_grad_()
b1=f(a1)
b1.sum().backward(retain_graph=True)#retain_graph=True，经测试控制流连续反向传播会报错，清除梯度也没用！！
print(a1.grad)
#b1.backward()#若a是向量，b也是向量，没法直接用反向传播
b1.backward(torch.ones_like(a1))#对非标量调用`backward`需要传入一个`gradient`参数，该参数指定微分函数关于`self`的梯度
print(a1.grad)

tensor([0., 2., 4.])
tensor([0., 4., 8.])


In [58]:
a=torch.arange(3.0)
a.requires_grad_()
a1 = a
b1 = a1*a1
b=b1
b.sum().backward()
a.grad

tensor([0., 2., 4.])

In [60]:
x=torch.arange(0.0,4.0,0.1)

In [62]:
x=torch.arange(0.0,4.0,0.1)
x.requires_grad_()
y=torch.sin(x)
y.backward(torch.ones(len(x)))
plot(x,[y,x.grad],'x','y',legend=['f(x)',"f'(x)"])

NameError: name 'plot' is not defined